/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// UpdateVirtualCircuitRequestOneOf struct for UpdateVirtualCircuitRequestOneOf
type UpdateVirtualCircuitRequestOneOf struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	// Speed can be changed only if it is an interconnection on a Dedicated Port
	Speed *string  `json:"speed,omitempty"`
	Tags  []string `json:"tags,omitempty"`
	// A Virtual Network record UUID or the VNID of a Virtual Network in your project.
	Vnid *string `json:"vnid,omitempty"`
}

// NewUpdateVirtualCircuitRequestOneOf instantiates a new UpdateVirtualCircuitRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVirtualCircuitRequestOneOf() *UpdateVirtualCircuitRequestOneOf {
	this := UpdateVirtualCircuitRequestOneOf{}
	return &this
}

// NewUpdateVirtualCircuitRequestOneOfWithDefaults instantiates a new UpdateVirtualCircuitRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVirtualCircuitRequestOneOfWithDefaults() *UpdateVirtualCircuitRequestOneOf {
	this := UpdateVirtualCircuitRequestOneOf{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateVirtualCircuitRequestOneOf) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVirtualCircuitRequestOneOf) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateVirtualCircuitRequestOneOf) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateVirtualCircuitRequestOneOf) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateVirtualCircuitRequestOneOf) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVirtualCircuitRequestOneOf) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateVirtualCircuitRequestOneOf) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateVirtualCircuitRequestOneOf) SetName(v string) {
	o.Name = &v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *UpdateVirtualCircuitRequestOneOf) GetSpeed() string {
	if o == nil || o.Speed == nil {
		var ret string
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVirtualCircuitRequestOneOf) GetSpeedOk() (*string, bool) {
	if o == nil || o.Speed == nil {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *UpdateVirtualCircuitRequestOneOf) HasSpeed() bool {
	if o != nil && o.Speed != nil {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given string and assigns it to the Speed field.
func (o *UpdateVirtualCircuitRequestOneOf) SetSpeed(v string) {
	o.Speed = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UpdateVirtualCircuitRequestOneOf) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVirtualCircuitRequestOneOf) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateVirtualCircuitRequestOneOf) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *UpdateVirtualCircuitRequestOneOf) SetTags(v []string) {
	o.Tags = v
}

// GetVnid returns the Vnid field value if set, zero value otherwise.
func (o *UpdateVirtualCircuitRequestOneOf) GetVnid() string {
	if o == nil || o.Vnid == nil {
		var ret string
		return ret
	}
	return *o.Vnid
}

// GetVnidOk returns a tuple with the Vnid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVirtualCircuitRequestOneOf) GetVnidOk() (*string, bool) {
	if o == nil || o.Vnid == nil {
		return nil, false
	}
	return o.Vnid, true
}

// HasVnid returns a boolean if a field has been set.
func (o *UpdateVirtualCircuitRequestOneOf) HasVnid() bool {
	if o != nil && o.Vnid != nil {
		return true
	}

	return false
}

// SetVnid gets a reference to the given string and assigns it to the Vnid field.
func (o *UpdateVirtualCircuitRequestOneOf) SetVnid(v string) {
	o.Vnid = &v
}

func (o UpdateVirtualCircuitRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Speed != nil {
		toSerialize["speed"] = o.Speed
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Vnid != nil {
		toSerialize["vnid"] = o.Vnid
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateVirtualCircuitRequestOneOf struct {
	value *UpdateVirtualCircuitRequestOneOf
	isSet bool
}

func (v NullableUpdateVirtualCircuitRequestOneOf) Get() *UpdateVirtualCircuitRequestOneOf {
	return v.value
}

func (v *NullableUpdateVirtualCircuitRequestOneOf) Set(val *UpdateVirtualCircuitRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVirtualCircuitRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVirtualCircuitRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVirtualCircuitRequestOneOf(val *UpdateVirtualCircuitRequestOneOf) *NullableUpdateVirtualCircuitRequestOneOf {
	return &NullableUpdateVirtualCircuitRequestOneOf{value: val, isSet: true}
}

func (v NullableUpdateVirtualCircuitRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVirtualCircuitRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
