/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// FindDeviceById200ResponseActionsInner struct for FindDeviceById200ResponseActionsInner
type FindDeviceById200ResponseActionsInner struct {
	Type *string `json:"type,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewFindDeviceById200ResponseActionsInner instantiates a new FindDeviceById200ResponseActionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindDeviceById200ResponseActionsInner() *FindDeviceById200ResponseActionsInner {
	this := FindDeviceById200ResponseActionsInner{}
	return &this
}

// NewFindDeviceById200ResponseActionsInnerWithDefaults instantiates a new FindDeviceById200ResponseActionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindDeviceById200ResponseActionsInnerWithDefaults() *FindDeviceById200ResponseActionsInner {
	this := FindDeviceById200ResponseActionsInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FindDeviceById200ResponseActionsInner) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceById200ResponseActionsInner) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FindDeviceById200ResponseActionsInner) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FindDeviceById200ResponseActionsInner) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FindDeviceById200ResponseActionsInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceById200ResponseActionsInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FindDeviceById200ResponseActionsInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FindDeviceById200ResponseActionsInner) SetName(v string) {
	o.Name = &v
}

func (o FindDeviceById200ResponseActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableFindDeviceById200ResponseActionsInner struct {
	value *FindDeviceById200ResponseActionsInner
	isSet bool
}

func (v NullableFindDeviceById200ResponseActionsInner) Get() *FindDeviceById200ResponseActionsInner {
	return v.value
}

func (v *NullableFindDeviceById200ResponseActionsInner) Set(val *FindDeviceById200ResponseActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindDeviceById200ResponseActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindDeviceById200ResponseActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindDeviceById200ResponseActionsInner(val *FindDeviceById200ResponseActionsInner) *NullableFindDeviceById200ResponseActionsInner {
	return &NullableFindDeviceById200ResponseActionsInner{value: val, isSet: true}
}

func (v NullableFindDeviceById200ResponseActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindDeviceById200ResponseActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
