/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// FindDeviceUserdataByID200Response struct for FindDeviceUserdataByID200Response
type FindDeviceUserdataByID200Response struct {
	Userdata *string `json:"userdata,omitempty"`
}

// NewFindDeviceUserdataByID200Response instantiates a new FindDeviceUserdataByID200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindDeviceUserdataByID200Response() *FindDeviceUserdataByID200Response {
	this := FindDeviceUserdataByID200Response{}
	return &this
}

// NewFindDeviceUserdataByID200ResponseWithDefaults instantiates a new FindDeviceUserdataByID200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindDeviceUserdataByID200ResponseWithDefaults() *FindDeviceUserdataByID200Response {
	this := FindDeviceUserdataByID200Response{}
	return &this
}

// GetUserdata returns the Userdata field value if set, zero value otherwise.
func (o *FindDeviceUserdataByID200Response) GetUserdata() string {
	if o == nil || o.Userdata == nil {
		var ret string
		return ret
	}
	return *o.Userdata
}

// GetUserdataOk returns a tuple with the Userdata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceUserdataByID200Response) GetUserdataOk() (*string, bool) {
	if o == nil || o.Userdata == nil {
		return nil, false
	}
	return o.Userdata, true
}

// HasUserdata returns a boolean if a field has been set.
func (o *FindDeviceUserdataByID200Response) HasUserdata() bool {
	if o != nil && o.Userdata != nil {
		return true
	}

	return false
}

// SetUserdata gets a reference to the given string and assigns it to the Userdata field.
func (o *FindDeviceUserdataByID200Response) SetUserdata(v string) {
	o.Userdata = &v
}

func (o FindDeviceUserdataByID200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Userdata != nil {
		toSerialize["userdata"] = o.Userdata
	}
	return json.Marshal(toSerialize)
}

type NullableFindDeviceUserdataByID200Response struct {
	value *FindDeviceUserdataByID200Response
	isSet bool
}

func (v NullableFindDeviceUserdataByID200Response) Get() *FindDeviceUserdataByID200Response {
	return v.value
}

func (v *NullableFindDeviceUserdataByID200Response) Set(val *FindDeviceUserdataByID200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindDeviceUserdataByID200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindDeviceUserdataByID200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindDeviceUserdataByID200Response(val *FindDeviceUserdataByID200Response) *NullableFindDeviceUserdataByID200Response {
	return &NullableFindDeviceUserdataByID200Response{value: val, isSet: true}
}

func (v NullableFindDeviceUserdataByID200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindDeviceUserdataByID200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
