/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
	_ "time"
)

// CreateDeviceRequest - struct for CreateDeviceRequest
type CreateDeviceRequest struct {
	CreateDeviceRequestOneOf  *CreateDeviceRequestOneOf
	CreateDeviceRequestOneOf1 *CreateDeviceRequestOneOf1
}

// CreateDeviceRequestOneOfAsCreateDeviceRequest is a convenience function that returns CreateDeviceRequestOneOf wrapped in CreateDeviceRequest
func CreateDeviceRequestOneOfAsCreateDeviceRequest(v *CreateDeviceRequestOneOf) CreateDeviceRequest {
	return CreateDeviceRequest{
		CreateDeviceRequestOneOf: v,
	}
}

// CreateDeviceRequestOneOf1AsCreateDeviceRequest is a convenience function that returns CreateDeviceRequestOneOf1 wrapped in CreateDeviceRequest
func CreateDeviceRequestOneOf1AsCreateDeviceRequest(v *CreateDeviceRequestOneOf1) CreateDeviceRequest {
	return CreateDeviceRequest{
		CreateDeviceRequestOneOf1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateDeviceRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateDeviceRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateDeviceRequestOneOf)
	if err == nil {
		jsonCreateDeviceRequestOneOf, _ := json.Marshal(dst.CreateDeviceRequestOneOf)
		if string(jsonCreateDeviceRequestOneOf) == "{}" { // empty struct
			dst.CreateDeviceRequestOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CreateDeviceRequestOneOf = nil
	}

	// try to unmarshal data into CreateDeviceRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.CreateDeviceRequestOneOf1)
	if err == nil {
		jsonCreateDeviceRequestOneOf1, _ := json.Marshal(dst.CreateDeviceRequestOneOf1)
		if string(jsonCreateDeviceRequestOneOf1) == "{}" { // empty struct
			dst.CreateDeviceRequestOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.CreateDeviceRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateDeviceRequestOneOf = nil
		dst.CreateDeviceRequestOneOf1 = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CreateDeviceRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CreateDeviceRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateDeviceRequest) MarshalJSON() ([]byte, error) {
	if src.CreateDeviceRequestOneOf != nil {
		return json.Marshal(&src.CreateDeviceRequestOneOf)
	}

	if src.CreateDeviceRequestOneOf1 != nil {
		return json.Marshal(&src.CreateDeviceRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateDeviceRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CreateDeviceRequestOneOf != nil {
		return obj.CreateDeviceRequestOneOf
	}

	if obj.CreateDeviceRequestOneOf1 != nil {
		return obj.CreateDeviceRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableCreateDeviceRequest struct {
	value *CreateDeviceRequest
	isSet bool
}

func (v NullableCreateDeviceRequest) Get() *CreateDeviceRequest {
	return v.value
}

func (v *NullableCreateDeviceRequest) Set(val *CreateDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeviceRequest(val *CreateDeviceRequest) *NullableCreateDeviceRequest {
	return &NullableCreateDeviceRequest{value: val, isSet: true}
}

func (v NullableCreateDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
