/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// FindTrafficTimeframeParameter struct for FindTrafficTimeframeParameter
type FindTrafficTimeframeParameter struct {
	EndedAt   time.Time `json:"ended_at"`
	StartedAt time.Time `json:"started_at"`
}

// NewFindTrafficTimeframeParameter instantiates a new FindTrafficTimeframeParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindTrafficTimeframeParameter(endedAt time.Time, startedAt time.Time) *FindTrafficTimeframeParameter {
	this := FindTrafficTimeframeParameter{}
	this.EndedAt = endedAt
	this.StartedAt = startedAt
	return &this
}

// NewFindTrafficTimeframeParameterWithDefaults instantiates a new FindTrafficTimeframeParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindTrafficTimeframeParameterWithDefaults() *FindTrafficTimeframeParameter {
	this := FindTrafficTimeframeParameter{}
	return &this
}

// GetEndedAt returns the EndedAt field value
func (o *FindTrafficTimeframeParameter) GetEndedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value
// and a boolean to check if the value has been set.
func (o *FindTrafficTimeframeParameter) GetEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndedAt, true
}

// SetEndedAt sets field value
func (o *FindTrafficTimeframeParameter) SetEndedAt(v time.Time) {
	o.EndedAt = v
}

// GetStartedAt returns the StartedAt field value
func (o *FindTrafficTimeframeParameter) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *FindTrafficTimeframeParameter) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *FindTrafficTimeframeParameter) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

func (o FindTrafficTimeframeParameter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ended_at"] = o.EndedAt
	}
	if true {
		toSerialize["started_at"] = o.StartedAt
	}
	return json.Marshal(toSerialize)
}

type NullableFindTrafficTimeframeParameter struct {
	value *FindTrafficTimeframeParameter
	isSet bool
}

func (v NullableFindTrafficTimeframeParameter) Get() *FindTrafficTimeframeParameter {
	return v.value
}

func (v *NullableFindTrafficTimeframeParameter) Set(val *FindTrafficTimeframeParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableFindTrafficTimeframeParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableFindTrafficTimeframeParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindTrafficTimeframeParameter(val *FindTrafficTimeframeParameter) *NullableFindTrafficTimeframeParameter {
	return &NullableFindTrafficTimeframeParameter{value: val, isSet: true}
}

func (v NullableFindTrafficTimeframeParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindTrafficTimeframeParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
