/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// CreateMetalGatewayRequestOneOf1 struct for CreateMetalGatewayRequestOneOf1
type CreateMetalGatewayRequestOneOf1 struct {
	// The UUID an a VRF IP Reservation that belongs to the same project as the one in which the Metal Gateway is to be created. Additionally, the VRF IP Reservation and the Virtual Network must reside in the same Metro.
	IpReservationId string `json:"ip_reservation_id"`
	// THe UUID of a Metro Virtual Network that belongs to the same project as the one in which the Metal Gateway is to be created. Additionally, the Virtual Network and the VRF IP Reservation must reside in the same metro.
	VirtualNetworkId string `json:"virtual_network_id"`
}

// NewCreateMetalGatewayRequestOneOf1 instantiates a new CreateMetalGatewayRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMetalGatewayRequestOneOf1(ipReservationId string, virtualNetworkId string) *CreateMetalGatewayRequestOneOf1 {
	this := CreateMetalGatewayRequestOneOf1{}
	this.IpReservationId = ipReservationId
	this.VirtualNetworkId = virtualNetworkId
	return &this
}

// NewCreateMetalGatewayRequestOneOf1WithDefaults instantiates a new CreateMetalGatewayRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMetalGatewayRequestOneOf1WithDefaults() *CreateMetalGatewayRequestOneOf1 {
	this := CreateMetalGatewayRequestOneOf1{}
	return &this
}

// GetIpReservationId returns the IpReservationId field value
func (o *CreateMetalGatewayRequestOneOf1) GetIpReservationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpReservationId
}

// GetIpReservationIdOk returns a tuple with the IpReservationId field value
// and a boolean to check if the value has been set.
func (o *CreateMetalGatewayRequestOneOf1) GetIpReservationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpReservationId, true
}

// SetIpReservationId sets field value
func (o *CreateMetalGatewayRequestOneOf1) SetIpReservationId(v string) {
	o.IpReservationId = v
}

// GetVirtualNetworkId returns the VirtualNetworkId field value
func (o *CreateMetalGatewayRequestOneOf1) GetVirtualNetworkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VirtualNetworkId
}

// GetVirtualNetworkIdOk returns a tuple with the VirtualNetworkId field value
// and a boolean to check if the value has been set.
func (o *CreateMetalGatewayRequestOneOf1) GetVirtualNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualNetworkId, true
}

// SetVirtualNetworkId sets field value
func (o *CreateMetalGatewayRequestOneOf1) SetVirtualNetworkId(v string) {
	o.VirtualNetworkId = v
}

func (o CreateMetalGatewayRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ip_reservation_id"] = o.IpReservationId
	}
	if true {
		toSerialize["virtual_network_id"] = o.VirtualNetworkId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateMetalGatewayRequestOneOf1 struct {
	value *CreateMetalGatewayRequestOneOf1
	isSet bool
}

func (v NullableCreateMetalGatewayRequestOneOf1) Get() *CreateMetalGatewayRequestOneOf1 {
	return v.value
}

func (v *NullableCreateMetalGatewayRequestOneOf1) Set(val *CreateMetalGatewayRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMetalGatewayRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMetalGatewayRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMetalGatewayRequestOneOf1(val *CreateMetalGatewayRequestOneOf1) *NullableCreateMetalGatewayRequestOneOf1 {
	return &NullableCreateMetalGatewayRequestOneOf1{value: val, isSet: true}
}

func (v NullableCreateMetalGatewayRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMetalGatewayRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
