/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// CreateMetalGatewayRequest - struct for CreateMetalGatewayRequest
type CreateMetalGatewayRequest struct {
	CreateMetalGatewayRequestOneOf  *CreateMetalGatewayRequestOneOf
	CreateMetalGatewayRequestOneOf1 *CreateMetalGatewayRequestOneOf1
}

// CreateMetalGatewayRequestOneOfAsCreateMetalGatewayRequest is a convenience function that returns CreateMetalGatewayRequestOneOf wrapped in CreateMetalGatewayRequest
func CreateMetalGatewayRequestOneOfAsCreateMetalGatewayRequest(v *CreateMetalGatewayRequestOneOf) CreateMetalGatewayRequest {
	return CreateMetalGatewayRequest{
		CreateMetalGatewayRequestOneOf: v,
	}
}

// CreateMetalGatewayRequestOneOf1AsCreateMetalGatewayRequest is a convenience function that returns CreateMetalGatewayRequestOneOf1 wrapped in CreateMetalGatewayRequest
func CreateMetalGatewayRequestOneOf1AsCreateMetalGatewayRequest(v *CreateMetalGatewayRequestOneOf1) CreateMetalGatewayRequest {
	return CreateMetalGatewayRequest{
		CreateMetalGatewayRequestOneOf1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateMetalGatewayRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateMetalGatewayRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateMetalGatewayRequestOneOf)
	if err == nil {
		jsonCreateMetalGatewayRequestOneOf, _ := json.Marshal(dst.CreateMetalGatewayRequestOneOf)
		if string(jsonCreateMetalGatewayRequestOneOf) == "{}" { // empty struct
			dst.CreateMetalGatewayRequestOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CreateMetalGatewayRequestOneOf = nil
	}

	// try to unmarshal data into CreateMetalGatewayRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.CreateMetalGatewayRequestOneOf1)
	if err == nil {
		jsonCreateMetalGatewayRequestOneOf1, _ := json.Marshal(dst.CreateMetalGatewayRequestOneOf1)
		if string(jsonCreateMetalGatewayRequestOneOf1) == "{}" { // empty struct
			dst.CreateMetalGatewayRequestOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.CreateMetalGatewayRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateMetalGatewayRequestOneOf = nil
		dst.CreateMetalGatewayRequestOneOf1 = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CreateMetalGatewayRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CreateMetalGatewayRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateMetalGatewayRequest) MarshalJSON() ([]byte, error) {
	if src.CreateMetalGatewayRequestOneOf != nil {
		return json.Marshal(&src.CreateMetalGatewayRequestOneOf)
	}

	if src.CreateMetalGatewayRequestOneOf1 != nil {
		return json.Marshal(&src.CreateMetalGatewayRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateMetalGatewayRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CreateMetalGatewayRequestOneOf != nil {
		return obj.CreateMetalGatewayRequestOneOf
	}

	if obj.CreateMetalGatewayRequestOneOf1 != nil {
		return obj.CreateMetalGatewayRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableCreateMetalGatewayRequest struct {
	value *CreateMetalGatewayRequest
	isSet bool
}

func (v NullableCreateMetalGatewayRequest) Get() *CreateMetalGatewayRequest {
	return v.value
}

func (v *NullableCreateMetalGatewayRequest) Set(val *CreateMetalGatewayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMetalGatewayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMetalGatewayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMetalGatewayRequest(val *CreateMetalGatewayRequest) *NullableCreateMetalGatewayRequest {
	return &NullableCreateMetalGatewayRequest{value: val, isSet: true}
}

func (v NullableCreateMetalGatewayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMetalGatewayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
