/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// CreateDeviceRequestOneOfAllOf1SshKeysInner struct for CreateDeviceRequestOneOfAllOf1SshKeysInner
type CreateDeviceRequestOneOfAllOf1SshKeysInner struct {
	Key   *string `json:"key,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewCreateDeviceRequestOneOfAllOf1SshKeysInner instantiates a new CreateDeviceRequestOneOfAllOf1SshKeysInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeviceRequestOneOfAllOf1SshKeysInner() *CreateDeviceRequestOneOfAllOf1SshKeysInner {
	this := CreateDeviceRequestOneOfAllOf1SshKeysInner{}
	return &this
}

// NewCreateDeviceRequestOneOfAllOf1SshKeysInnerWithDefaults instantiates a new CreateDeviceRequestOneOfAllOf1SshKeysInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeviceRequestOneOfAllOf1SshKeysInnerWithDefaults() *CreateDeviceRequestOneOfAllOf1SshKeysInner {
	this := CreateDeviceRequestOneOfAllOf1SshKeysInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) SetKey(v string) {
	o.Key = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CreateDeviceRequestOneOfAllOf1SshKeysInner) SetLabel(v string) {
	o.Label = &v
}

func (o CreateDeviceRequestOneOfAllOf1SshKeysInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	return json.Marshal(toSerialize)
}

type NullableCreateDeviceRequestOneOfAllOf1SshKeysInner struct {
	value *CreateDeviceRequestOneOfAllOf1SshKeysInner
	isSet bool
}

func (v NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) Get() *CreateDeviceRequestOneOfAllOf1SshKeysInner {
	return v.value
}

func (v *NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) Set(val *CreateDeviceRequestOneOfAllOf1SshKeysInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeviceRequestOneOfAllOf1SshKeysInner(val *CreateDeviceRequestOneOfAllOf1SshKeysInner) *NullableCreateDeviceRequestOneOfAllOf1SshKeysInner {
	return &NullableCreateDeviceRequestOneOfAllOf1SshKeysInner{value: val, isSet: true}
}

func (v NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeviceRequestOneOfAllOf1SshKeysInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
