/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// RequestIPReservationRequest - struct for RequestIPReservationRequest
type RequestIPReservationRequest struct {
	RequestIPReservationRequestOneOf  *RequestIPReservationRequestOneOf
	RequestIPReservationRequestOneOf1 *RequestIPReservationRequestOneOf1
}

// RequestIPReservationRequestOneOfAsRequestIPReservationRequest is a convenience function that returns RequestIPReservationRequestOneOf wrapped in RequestIPReservationRequest
func RequestIPReservationRequestOneOfAsRequestIPReservationRequest(v *RequestIPReservationRequestOneOf) RequestIPReservationRequest {
	return RequestIPReservationRequest{
		RequestIPReservationRequestOneOf: v,
	}
}

// RequestIPReservationRequestOneOf1AsRequestIPReservationRequest is a convenience function that returns RequestIPReservationRequestOneOf1 wrapped in RequestIPReservationRequest
func RequestIPReservationRequestOneOf1AsRequestIPReservationRequest(v *RequestIPReservationRequestOneOf1) RequestIPReservationRequest {
	return RequestIPReservationRequest{
		RequestIPReservationRequestOneOf1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestIPReservationRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RequestIPReservationRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.RequestIPReservationRequestOneOf)
	if err == nil {
		jsonRequestIPReservationRequestOneOf, _ := json.Marshal(dst.RequestIPReservationRequestOneOf)
		if string(jsonRequestIPReservationRequestOneOf) == "{}" { // empty struct
			dst.RequestIPReservationRequestOneOf = nil
		} else {
			match++
		}
	} else {
		dst.RequestIPReservationRequestOneOf = nil
	}

	// try to unmarshal data into RequestIPReservationRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.RequestIPReservationRequestOneOf1)
	if err == nil {
		jsonRequestIPReservationRequestOneOf1, _ := json.Marshal(dst.RequestIPReservationRequestOneOf1)
		if string(jsonRequestIPReservationRequestOneOf1) == "{}" { // empty struct
			dst.RequestIPReservationRequestOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.RequestIPReservationRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RequestIPReservationRequestOneOf = nil
		dst.RequestIPReservationRequestOneOf1 = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(RequestIPReservationRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(RequestIPReservationRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestIPReservationRequest) MarshalJSON() ([]byte, error) {
	if src.RequestIPReservationRequestOneOf != nil {
		return json.Marshal(&src.RequestIPReservationRequestOneOf)
	}

	if src.RequestIPReservationRequestOneOf1 != nil {
		return json.Marshal(&src.RequestIPReservationRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestIPReservationRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.RequestIPReservationRequestOneOf != nil {
		return obj.RequestIPReservationRequestOneOf
	}

	if obj.RequestIPReservationRequestOneOf1 != nil {
		return obj.RequestIPReservationRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableRequestIPReservationRequest struct {
	value *RequestIPReservationRequest
	isSet bool
}

func (v NullableRequestIPReservationRequest) Get() *RequestIPReservationRequest {
	return v.value
}

func (v *NullableRequestIPReservationRequest) Set(val *RequestIPReservationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestIPReservationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestIPReservationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestIPReservationRequest(val *RequestIPReservationRequest) *NullableRequestIPReservationRequest {
	return &NullableRequestIPReservationRequest{value: val, isSet: true}
}

func (v NullableRequestIPReservationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestIPReservationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
