/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// FindIPAddressById200ResponseOneOf struct for FindIPAddressById200ResponseOneOf
type FindIPAddressById200ResponseOneOf struct {
	Addon         *bool                                                                             `json:"addon,omitempty"`
	AddressFamily *int32                                                                            `json:"address_family,omitempty"`
	Assignments   []FindDeviceById200ResponseIpAddressesInner                                       `json:"assignments,omitempty"`
	Bill          *bool                                                                             `json:"bill,omitempty"`
	Cidr          *int32                                                                            `json:"cidr,omitempty"`
	CreatedAt     *time.Time                                                                        `json:"created_at,omitempty"`
	Enabled       *bool                                                                             `json:"enabled,omitempty"`
	Facility      *FindIPAddressById200ResponseOneOfFacility                                        `json:"facility,omitempty"`
	GlobalIp      *bool                                                                             `json:"global_ip,omitempty"`
	Href          *string                                                                           `json:"href,omitempty"`
	Id            *string                                                                           `json:"id,omitempty"`
	Manageable    *bool                                                                             `json:"manageable,omitempty"`
	Management    *bool                                                                             `json:"management,omitempty"`
	MetalGateway  *FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner `json:"metal_gateway,omitempty"`
	Metro         *FindIPAddressById200ResponseOneOfMetro                                           `json:"metro,omitempty"`
	Netmask       *string                                                                           `json:"netmask,omitempty"`
	Network       *string                                                                           `json:"network,omitempty"`
	Public        *bool                                                                             `json:"public,omitempty"`
	State         *string                                                                           `json:"state,omitempty"`
	Tags          []string                                                                          `json:"tags,omitempty"`
}

// NewFindIPAddressById200ResponseOneOf instantiates a new FindIPAddressById200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindIPAddressById200ResponseOneOf() *FindIPAddressById200ResponseOneOf {
	this := FindIPAddressById200ResponseOneOf{}
	return &this
}

// NewFindIPAddressById200ResponseOneOfWithDefaults instantiates a new FindIPAddressById200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindIPAddressById200ResponseOneOfWithDefaults() *FindIPAddressById200ResponseOneOf {
	this := FindIPAddressById200ResponseOneOf{}
	return &this
}

// GetAddon returns the Addon field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetAddon() bool {
	if o == nil || o.Addon == nil {
		var ret bool
		return ret
	}
	return *o.Addon
}

// GetAddonOk returns a tuple with the Addon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetAddonOk() (*bool, bool) {
	if o == nil || o.Addon == nil {
		return nil, false
	}
	return o.Addon, true
}

// HasAddon returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasAddon() bool {
	if o != nil && o.Addon != nil {
		return true
	}

	return false
}

// SetAddon gets a reference to the given bool and assigns it to the Addon field.
func (o *FindIPAddressById200ResponseOneOf) SetAddon(v bool) {
	o.Addon = &v
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetAddressFamily() int32 {
	if o == nil || o.AddressFamily == nil {
		var ret int32
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetAddressFamilyOk() (*int32, bool) {
	if o == nil || o.AddressFamily == nil {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasAddressFamily() bool {
	if o != nil && o.AddressFamily != nil {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given int32 and assigns it to the AddressFamily field.
func (o *FindIPAddressById200ResponseOneOf) SetAddressFamily(v int32) {
	o.AddressFamily = &v
}

// GetAssignments returns the Assignments field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetAssignments() []FindDeviceById200ResponseIpAddressesInner {
	if o == nil || o.Assignments == nil {
		var ret []FindDeviceById200ResponseIpAddressesInner
		return ret
	}
	return o.Assignments
}

// GetAssignmentsOk returns a tuple with the Assignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetAssignmentsOk() ([]FindDeviceById200ResponseIpAddressesInner, bool) {
	if o == nil || o.Assignments == nil {
		return nil, false
	}
	return o.Assignments, true
}

// HasAssignments returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasAssignments() bool {
	if o != nil && o.Assignments != nil {
		return true
	}

	return false
}

// SetAssignments gets a reference to the given []FindDeviceById200ResponseIpAddressesInner and assigns it to the Assignments field.
func (o *FindIPAddressById200ResponseOneOf) SetAssignments(v []FindDeviceById200ResponseIpAddressesInner) {
	o.Assignments = v
}

// GetBill returns the Bill field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetBill() bool {
	if o == nil || o.Bill == nil {
		var ret bool
		return ret
	}
	return *o.Bill
}

// GetBillOk returns a tuple with the Bill field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetBillOk() (*bool, bool) {
	if o == nil || o.Bill == nil {
		return nil, false
	}
	return o.Bill, true
}

// HasBill returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasBill() bool {
	if o != nil && o.Bill != nil {
		return true
	}

	return false
}

// SetBill gets a reference to the given bool and assigns it to the Bill field.
func (o *FindIPAddressById200ResponseOneOf) SetBill(v bool) {
	o.Bill = &v
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetCidr() int32 {
	if o == nil || o.Cidr == nil {
		var ret int32
		return ret
	}
	return *o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetCidrOk() (*int32, bool) {
	if o == nil || o.Cidr == nil {
		return nil, false
	}
	return o.Cidr, true
}

// HasCidr returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasCidr() bool {
	if o != nil && o.Cidr != nil {
		return true
	}

	return false
}

// SetCidr gets a reference to the given int32 and assigns it to the Cidr field.
func (o *FindIPAddressById200ResponseOneOf) SetCidr(v int32) {
	o.Cidr = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FindIPAddressById200ResponseOneOf) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *FindIPAddressById200ResponseOneOf) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetFacility returns the Facility field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetFacility() FindIPAddressById200ResponseOneOfFacility {
	if o == nil || o.Facility == nil {
		var ret FindIPAddressById200ResponseOneOfFacility
		return ret
	}
	return *o.Facility
}

// GetFacilityOk returns a tuple with the Facility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetFacilityOk() (*FindIPAddressById200ResponseOneOfFacility, bool) {
	if o == nil || o.Facility == nil {
		return nil, false
	}
	return o.Facility, true
}

// HasFacility returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasFacility() bool {
	if o != nil && o.Facility != nil {
		return true
	}

	return false
}

// SetFacility gets a reference to the given FindIPAddressById200ResponseOneOfFacility and assigns it to the Facility field.
func (o *FindIPAddressById200ResponseOneOf) SetFacility(v FindIPAddressById200ResponseOneOfFacility) {
	o.Facility = &v
}

// GetGlobalIp returns the GlobalIp field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetGlobalIp() bool {
	if o == nil || o.GlobalIp == nil {
		var ret bool
		return ret
	}
	return *o.GlobalIp
}

// GetGlobalIpOk returns a tuple with the GlobalIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetGlobalIpOk() (*bool, bool) {
	if o == nil || o.GlobalIp == nil {
		return nil, false
	}
	return o.GlobalIp, true
}

// HasGlobalIp returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasGlobalIp() bool {
	if o != nil && o.GlobalIp != nil {
		return true
	}

	return false
}

// SetGlobalIp gets a reference to the given bool and assigns it to the GlobalIp field.
func (o *FindIPAddressById200ResponseOneOf) SetGlobalIp(v bool) {
	o.GlobalIp = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *FindIPAddressById200ResponseOneOf) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FindIPAddressById200ResponseOneOf) SetId(v string) {
	o.Id = &v
}

// GetManageable returns the Manageable field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetManageable() bool {
	if o == nil || o.Manageable == nil {
		var ret bool
		return ret
	}
	return *o.Manageable
}

// GetManageableOk returns a tuple with the Manageable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetManageableOk() (*bool, bool) {
	if o == nil || o.Manageable == nil {
		return nil, false
	}
	return o.Manageable, true
}

// HasManageable returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasManageable() bool {
	if o != nil && o.Manageable != nil {
		return true
	}

	return false
}

// SetManageable gets a reference to the given bool and assigns it to the Manageable field.
func (o *FindIPAddressById200ResponseOneOf) SetManageable(v bool) {
	o.Manageable = &v
}

// GetManagement returns the Management field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetManagement() bool {
	if o == nil || o.Management == nil {
		var ret bool
		return ret
	}
	return *o.Management
}

// GetManagementOk returns a tuple with the Management field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetManagementOk() (*bool, bool) {
	if o == nil || o.Management == nil {
		return nil, false
	}
	return o.Management, true
}

// HasManagement returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasManagement() bool {
	if o != nil && o.Management != nil {
		return true
	}

	return false
}

// SetManagement gets a reference to the given bool and assigns it to the Management field.
func (o *FindIPAddressById200ResponseOneOf) SetManagement(v bool) {
	o.Management = &v
}

// GetMetalGateway returns the MetalGateway field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetMetalGateway() FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner {
	if o == nil || o.MetalGateway == nil {
		var ret FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner
		return ret
	}
	return *o.MetalGateway
}

// GetMetalGatewayOk returns a tuple with the MetalGateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetMetalGatewayOk() (*FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner, bool) {
	if o == nil || o.MetalGateway == nil {
		return nil, false
	}
	return o.MetalGateway, true
}

// HasMetalGateway returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasMetalGateway() bool {
	if o != nil && o.MetalGateway != nil {
		return true
	}

	return false
}

// SetMetalGateway gets a reference to the given FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner and assigns it to the MetalGateway field.
func (o *FindIPAddressById200ResponseOneOf) SetMetalGateway(v FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner) {
	o.MetalGateway = &v
}

// GetMetro returns the Metro field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetMetro() FindIPAddressById200ResponseOneOfMetro {
	if o == nil || o.Metro == nil {
		var ret FindIPAddressById200ResponseOneOfMetro
		return ret
	}
	return *o.Metro
}

// GetMetroOk returns a tuple with the Metro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetMetroOk() (*FindIPAddressById200ResponseOneOfMetro, bool) {
	if o == nil || o.Metro == nil {
		return nil, false
	}
	return o.Metro, true
}

// HasMetro returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasMetro() bool {
	if o != nil && o.Metro != nil {
		return true
	}

	return false
}

// SetMetro gets a reference to the given FindIPAddressById200ResponseOneOfMetro and assigns it to the Metro field.
func (o *FindIPAddressById200ResponseOneOf) SetMetro(v FindIPAddressById200ResponseOneOfMetro) {
	o.Metro = &v
}

// GetNetmask returns the Netmask field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetNetmask() string {
	if o == nil || o.Netmask == nil {
		var ret string
		return ret
	}
	return *o.Netmask
}

// GetNetmaskOk returns a tuple with the Netmask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetNetmaskOk() (*string, bool) {
	if o == nil || o.Netmask == nil {
		return nil, false
	}
	return o.Netmask, true
}

// HasNetmask returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasNetmask() bool {
	if o != nil && o.Netmask != nil {
		return true
	}

	return false
}

// SetNetmask gets a reference to the given string and assigns it to the Netmask field.
func (o *FindIPAddressById200ResponseOneOf) SetNetmask(v string) {
	o.Netmask = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetNetwork() string {
	if o == nil || o.Network == nil {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetNetworkOk() (*string, bool) {
	if o == nil || o.Network == nil {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasNetwork() bool {
	if o != nil && o.Network != nil {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *FindIPAddressById200ResponseOneOf) SetNetwork(v string) {
	o.Network = &v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetPublic() bool {
	if o == nil || o.Public == nil {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetPublicOk() (*bool, bool) {
	if o == nil || o.Public == nil {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasPublic() bool {
	if o != nil && o.Public != nil {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *FindIPAddressById200ResponseOneOf) SetPublic(v bool) {
	o.Public = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *FindIPAddressById200ResponseOneOf) SetState(v string) {
	o.State = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *FindIPAddressById200ResponseOneOf) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindIPAddressById200ResponseOneOf) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *FindIPAddressById200ResponseOneOf) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *FindIPAddressById200ResponseOneOf) SetTags(v []string) {
	o.Tags = v
}

func (o FindIPAddressById200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Addon != nil {
		toSerialize["addon"] = o.Addon
	}
	if o.AddressFamily != nil {
		toSerialize["address_family"] = o.AddressFamily
	}
	if o.Assignments != nil {
		toSerialize["assignments"] = o.Assignments
	}
	if o.Bill != nil {
		toSerialize["bill"] = o.Bill
	}
	if o.Cidr != nil {
		toSerialize["cidr"] = o.Cidr
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Facility != nil {
		toSerialize["facility"] = o.Facility
	}
	if o.GlobalIp != nil {
		toSerialize["global_ip"] = o.GlobalIp
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Manageable != nil {
		toSerialize["manageable"] = o.Manageable
	}
	if o.Management != nil {
		toSerialize["management"] = o.Management
	}
	if o.MetalGateway != nil {
		toSerialize["metal_gateway"] = o.MetalGateway
	}
	if o.Metro != nil {
		toSerialize["metro"] = o.Metro
	}
	if o.Netmask != nil {
		toSerialize["netmask"] = o.Netmask
	}
	if o.Network != nil {
		toSerialize["network"] = o.Network
	}
	if o.Public != nil {
		toSerialize["public"] = o.Public
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableFindIPAddressById200ResponseOneOf struct {
	value *FindIPAddressById200ResponseOneOf
	isSet bool
}

func (v NullableFindIPAddressById200ResponseOneOf) Get() *FindIPAddressById200ResponseOneOf {
	return v.value
}

func (v *NullableFindIPAddressById200ResponseOneOf) Set(val *FindIPAddressById200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableFindIPAddressById200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableFindIPAddressById200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindIPAddressById200ResponseOneOf(val *FindIPAddressById200ResponseOneOf) *NullableFindIPAddressById200ResponseOneOf {
	return &NullableFindIPAddressById200ResponseOneOf{value: val, isSet: true}
}

func (v NullableFindIPAddressById200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindIPAddressById200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
