/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner struct for GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner
type GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner struct {
	GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf  *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf
	GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1 *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf
	err = json.Unmarshal(data, &dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf)
	if err == nil {
		jsonGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf, _ := json.Marshal(dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf)
		if string(jsonGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf) == "{}" { // empty struct
			dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf = nil
		} else {
			return nil // data stored in dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf, return on the first match
		}
	} else {
		dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf = nil
	}

	// try to unmarshal JSON data into GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1
	err = json.Unmarshal(data, &dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1)
	if err == nil {
		jsonGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1, _ := json.Marshal(dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1)
		if string(jsonGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1) == "{}" { // empty struct
			dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1 = nil
		} else {
			return nil // data stored in dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1, return on the first match
		}
	} else {
		dst.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1 = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) MarshalJSON() ([]byte, error) {
	if src.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf != nil {
		return json.Marshal(&src.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf)
	}

	if src.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1 != nil {
		return json.Marshal(&src.GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner struct {
	value *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner
	isSet bool
}

func (v NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) Get() *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner {
	return v.value
}

func (v *NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) Set(val *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner(val *GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) *NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner {
	return &NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner{value: val, isSet: true}
}

func (v NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
