/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ListInterconnectionPorts200Response struct for ListInterconnectionPorts200Response
type ListInterconnectionPorts200Response struct {
	Ports []GetInterconnection200ResponsePortsInner `json:"ports,omitempty"`
}

// NewListInterconnectionPorts200Response instantiates a new ListInterconnectionPorts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInterconnectionPorts200Response() *ListInterconnectionPorts200Response {
	this := ListInterconnectionPorts200Response{}
	return &this
}

// NewListInterconnectionPorts200ResponseWithDefaults instantiates a new ListInterconnectionPorts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInterconnectionPorts200ResponseWithDefaults() *ListInterconnectionPorts200Response {
	this := ListInterconnectionPorts200Response{}
	return &this
}

// GetPorts returns the Ports field value if set, zero value otherwise.
func (o *ListInterconnectionPorts200Response) GetPorts() []GetInterconnection200ResponsePortsInner {
	if o == nil || o.Ports == nil {
		var ret []GetInterconnection200ResponsePortsInner
		return ret
	}
	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListInterconnectionPorts200Response) GetPortsOk() ([]GetInterconnection200ResponsePortsInner, bool) {
	if o == nil || o.Ports == nil {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *ListInterconnectionPorts200Response) HasPorts() bool {
	if o != nil && o.Ports != nil {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []GetInterconnection200ResponsePortsInner and assigns it to the Ports field.
func (o *ListInterconnectionPorts200Response) SetPorts(v []GetInterconnection200ResponsePortsInner) {
	o.Ports = v
}

func (o ListInterconnectionPorts200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ports != nil {
		toSerialize["ports"] = o.Ports
	}
	return json.Marshal(toSerialize)
}

type NullableListInterconnectionPorts200Response struct {
	value *ListInterconnectionPorts200Response
	isSet bool
}

func (v NullableListInterconnectionPorts200Response) Get() *ListInterconnectionPorts200Response {
	return v.value
}

func (v *NullableListInterconnectionPorts200Response) Set(val *ListInterconnectionPorts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListInterconnectionPorts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListInterconnectionPorts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInterconnectionPorts200Response(val *ListInterconnectionPorts200Response) *NullableListInterconnectionPorts200Response {
	return &NullableListInterconnectionPorts200Response{value: val, isSet: true}
}

func (v NullableListInterconnectionPorts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInterconnectionPorts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
