/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateProject - Create a project
func CreateProject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateProjectInvitation - Create an invitation for a project
func CreateProjectInvitation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateTransferRequest - Create a transfer request
func CreateTransferRequest(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteProject - Delete the project
func DeleteProject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindIPReservationCustomdata - Retrieve the custom metadata of an IP Reservation
func FindIPReservationCustomdata(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectById - Retrieve a project
func FindProjectById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectCustomdata - Retrieve the custom metadata of a project
func FindProjectCustomdata(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectInvitations - Retrieve project invitations
func FindProjectInvitations(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectMemberships - Retrieve project memberships
func FindProjectMemberships(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjects - Retrieve all projects
func FindProjects(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateProject - Update the project
func UpdateProject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
