/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteBgpSession - Delete the BGP session
func DeleteBgpSession(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindBgpConfigByProject - Retrieve a bgp config
func FindBgpConfigByProject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindBgpSessionById - Retrieve a BGP session
func FindBgpSessionById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindGlobalBgpRanges - Retrieve all global bgp ranges
func FindGlobalBgpRanges(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectBgpSessions - Retrieve all BGP sessions for project
func FindProjectBgpSessions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RequestBgpConfig - Requesting bgp config
func RequestBgpConfig(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateBgpSession - Update the BGP session
func UpdateBgpSession(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
