/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AssignNativeVlan - Assign a native VLAN
func AssignNativeVlan(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AssignPort - Assign a port to virtual network
func AssignPort(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// BondPort - Enabling bonding
func BondPort(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ConvertLayer2 - Convert to Layer 2
func ConvertLayer2(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ConvertLayer3 - Convert to Layer 3
func ConvertLayer3(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreatePortVlanAssignmentBatch - Create a new Port-VLAN Assignment management batch
func CreatePortVlanAssignmentBatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteNativeVlan - Remove native VLAN
func DeleteNativeVlan(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DisbondPort - Disabling bonding
func DisbondPort(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPortById - Retrieve a port
func FindPortById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPortVlanAssignmentBatchByPortIdAndBatchId - Retrieve a VLAN Assignment Batch's details
func FindPortVlanAssignmentBatchByPortIdAndBatchId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPortVlanAssignmentBatches - List the VLAN Assignment Batches for a port
func FindPortVlanAssignmentBatches(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPortVlanAssignmentByPortIdAndAssignmentId - Show a particular Port VLAN assignment's details
func FindPortVlanAssignmentByPortIdAndAssignmentId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPortVlanAssignments - List Current VLAN assignments for a port
func FindPortVlanAssignments(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UnassignPort - Unassign a port
func UnassignPort(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
