/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DisableTfaApp - Disable two factor authentication
func DisableTfaApp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DisableTfaSms - Disable two factor authentication
func DisableTfaSms(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// EnableTfaApp - Enable two factor auth using app
func EnableTfaApp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// EnableTfaSms - Enable two factor auth using sms
func EnableTfaSms(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
