/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type UpdateCurrentUserRequest struct {
	Customdata map[string]interface{} `json:"customdata,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	Password string `json:"password,omitempty"`

	PhoneNumber string `json:"phone_number,omitempty"`

	Timezone string `json:"timezone,omitempty"`
}
