/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type SpotPricesPerFacility struct {
	Baremetal0 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_0,omitempty"`

	Baremetal1 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_1,omitempty"`

	Baremetal2 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_2,omitempty"`

	Baremetal2a FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_2a,omitempty"`

	Baremetal2a2 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_2a2,omitempty"`

	Baremetal3 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_3,omitempty"`

	BaremetalS FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"baremetal_s,omitempty"`

	C2MediumX86 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"c2.medium.x86,omitempty"`

	M2XlargeX86 FindSpotMarketPrices200ResponseSpotMarketPricesAms1Baremetal0 `json:"m2.xlarge.x86,omitempty"`
}
