/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1Vrf struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	// Optional field that can be set to describe the VRF
	Description string `json:"description,omitempty"`

	// A 4-byte ASN associated with the VRF.
	LocalAsn int32 `json:"local_asn,omitempty"`

	// A list of CIDR network addresses. Like [\"10.0.0.0/16\", \"2001:d78::/56\"].
	IpRanges []string `json:"ip_ranges,omitempty"`

	Project GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1VrfProject `json:"project,omitempty"`

	Metro GetInterconnection200ResponseMetroAllOf `json:"metro,omitempty"`

	CreatedBy GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1VrfCreatedBy `json:"created_by,omitempty"`

	Href string `json:"href,omitempty"`
}
