/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type User struct {
	AvatarThumbUrl string `json:"avatar_thumb_url,omitempty"`

	AvatarUrl string `json:"avatar_url,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Email string `json:"email,omitempty"`

	Emails []FindBatchById200ResponseDevicesInner `json:"emails,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	FraudScore string `json:"fraud_score,omitempty"`

	FullName string `json:"full_name,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	LastLoginAt time.Time `json:"last_login_at,omitempty"`

	LastName string `json:"last_name,omitempty"`

	MaxOrganizations int32 `json:"max_organizations,omitempty"`

	MaxProjects int32 `json:"max_projects,omitempty"`

	PhoneNumber string `json:"phone_number,omitempty"`

	ShortId string `json:"short_id,omitempty"`

	Timezone string `json:"timezone,omitempty"`

	TwoFactorAuth string `json:"two_factor_auth,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
