/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type ProjectUpdateInput struct {
	BackendTransferEnabled bool `json:"backend_transfer_enabled,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Name string `json:"name,omitempty"`

	PaymentMethodId string `json:"payment_method_id,omitempty"`
}
