/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type CreateSpotMarketRequestRequestInstanceAttributes struct {
	AlwaysPxe bool `json:"always_pxe,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Description string `json:"description,omitempty"`

	Features []string `json:"features,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	Hostnames []string `json:"hostnames,omitempty"`

	Locked bool `json:"locked,omitempty"`

	NoSshKeys bool `json:"no_ssh_keys,omitempty"`

	OperatingSystem string `json:"operating_system,omitempty"`

	Plan string `json:"plan,omitempty"`

	PrivateIpv4SubnetSize int32 `json:"private_ipv4_subnet_size,omitempty"`

	ProjectSshKeys []string `json:"project_ssh_keys,omitempty"`

	PublicIpv4SubnetSize int32 `json:"public_ipv4_subnet_size,omitempty"`

	Tags []string `json:"tags,omitempty"`

	TerminationTime time.Time `json:"termination_time,omitempty"`

	// The UUIDs of users whose SSH keys should be included on the provisioned device.
	UserSshKeys []string `json:"user_ssh_keys,omitempty"`

	Userdata string `json:"userdata,omitempty"`
}
