/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type Entitlement struct {
	Description string `json:"description,omitempty"`

	FeatureAccess map[string]interface{} `json:"feature_access,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id"`

	InstanceQuota map[string]interface{} `json:"instance_quota,omitempty"`

	IpQuota map[string]interface{} `json:"ip_quota,omitempty"`

	Name string `json:"name,omitempty"`

	ProjectQuota int32 `json:"project_quota,omitempty"`

	Slug string `json:"slug"`

	VolumeLimits map[string]interface{} `json:"volume_limits,omitempty"`

	VolumeQuota map[string]interface{} `json:"volume_quota,omitempty"`

	Weight int32 `json:"weight"`
}
