/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type Meta struct {
	First FindBatchById200ResponseDevicesInner `json:"first,omitempty"`

	Last FindBatchById200ResponseDevicesInner `json:"last,omitempty"`

	Next FindBatchById200ResponseDevicesInner `json:"next,omitempty"`

	Previous FindBatchById200ResponseDevicesInner `json:"previous,omitempty"`

	Self FindBatchById200ResponseDevicesInner `json:"self,omitempty"`

	Total int32 `json:"total,omitempty"`
}
