/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type Facility struct {
	Address FindDeviceById200ResponseFacilityAddress `json:"address,omitempty"`

	Code string `json:"code,omitempty"`

	Features []string `json:"features,omitempty"`

	Id string `json:"id,omitempty"`

	// IP ranges registered in facility. Can be used for GeoIP location
	IpRanges []string `json:"ip_ranges,omitempty"`

	Metro FindDeviceById200ResponseFacilityMetro `json:"metro,omitempty"`

	Name string `json:"name,omitempty"`
}
