/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type SpotMarketRequest struct {
	CreatedAt time.Time `json:"created_at,omitempty"`

	DevicesMax int32 `json:"devices_max,omitempty"`

	DevicesMin int32 `json:"devices_min,omitempty"`

	EndAt time.Time `json:"end_at,omitempty"`

	Facilities FindBatchById200ResponseDevicesInner `json:"facilities,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Instances FindBatchById200ResponseDevicesInner `json:"instances,omitempty"`

	MaxBidPrice float32 `json:"max_bid_price,omitempty"`

	Metro ListSpotMarketRequests200ResponseSpotMarketRequestsInnerMetro `json:"metro,omitempty"`

	Project FindBatchById200ResponseDevicesInner `json:"project,omitempty"`
}
