/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type FindInterconnectionEvents200Response struct {
	Body string `json:"body,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Interpolated string `json:"interpolated,omitempty"`

	Relationships []FindBatchById200ResponseDevicesInner `json:"relationships,omitempty"`

	State string `json:"state,omitempty"`

	Type string `json:"type,omitempty"`
}
