/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1VrfProject struct {
	BgpConfig FindBatchById200ResponseDevicesInner `json:"bgp_config,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Devices []FindBatchById200ResponseDevicesInner `json:"devices,omitempty"`

	Id string `json:"id,omitempty"`

	Invitations []FindBatchById200ResponseDevicesInner `json:"invitations,omitempty"`

	MaxDevices map[string]interface{} `json:"max_devices,omitempty"`

	Members []FindBatchById200ResponseDevicesInner `json:"members,omitempty"`

	Memberships []FindBatchById200ResponseDevicesInner `json:"memberships,omitempty"`

	Name string `json:"name,omitempty"`

	NetworkStatus map[string]interface{} `json:"network_status,omitempty"`

	PaymentMethod FindBatchById200ResponseDevicesInner `json:"payment_method,omitempty"`

	SshKeys []FindBatchById200ResponseDevicesInner `json:"ssh_keys,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	Volumes []FindBatchById200ResponseDevicesInner `json:"volumes,omitempty"`
}
