/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type BgpConfig struct {

	// Autonomous System Number. ASN is required with Global BGP. With Local BGP the private ASN, 65000, is assigned.
	Asn int32 `json:"asn,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	// In a Local BGP deployment, a customer uses an internal ASN to control routes within a single Equinix Metal datacenter. This means that the routes are never advertised to the global Internet. Global BGP, on the other hand, requires a customer to have a registered ASN and IP space.
	DeploymentType string `json:"deployment_type,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	// The maximum number of route filters allowed per server
	MaxPrefix int32 `json:"max_prefix,omitempty"`

	// (Optional) Password for BGP session in plaintext (not a checksum)
	Md5 *string `json:"md5,omitempty"`

	Project FindBatchById200ResponseDevicesInner `json:"project,omitempty"`

	// The IP block ranges associated to the ASN (Populated in Global BGP only)
	Ranges []FindBgpConfigByProject200ResponseRangesInner `json:"ranges,omitempty"`

	RequestedAt time.Time `json:"requested_at,omitempty"`

	// Specifies AS-MACRO (aka AS-SET) to use when building client route filters
	RouteObject string `json:"route_object,omitempty"`

	// The direct connections between neighboring routers that want to exchange routing information.
	Sessions []FindBgpSessionById200Response `json:"sessions,omitempty"`

	// Status of the BGP Config. Status \"requested\" is valid only with the \"global\" deployment_type.
	Status string `json:"status,omitempty"`
}
