/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type OperatingSystem struct {
	Distro string `json:"distro,omitempty"`

	Id string `json:"id,omitempty"`

	// Licenced OS is priced according to pricing property
	Licensed bool `json:"licensed,omitempty"`

	Name string `json:"name,omitempty"`

	// Servers can be already preinstalled with OS in order to shorten provision time.
	Preinstallable bool `json:"preinstallable,omitempty"`

	// This object contains price per time unit and optional multiplier value if licence price depends on hardware plan or components (e.g. number of cores)
	Pricing map[string]interface{} `json:"pricing,omitempty"`

	ProvisionableOn []string `json:"provisionable_on,omitempty"`

	Slug string `json:"slug,omitempty"`

	Version string `json:"version,omitempty"`
}
