/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type Plan struct {

	// Shows which facilities the plan is available in, and the facility-based price if it is different from the default price.
	AvailableIn []FindDeviceById200ResponsePlanAvailableInInner `json:"available_in,omitempty"`

	// Shows which metros the plan is available in, and the metro-based price if it is different from the default price.
	AvailableInMetros []FindDeviceById200ResponsePlanAvailableInMetrosInner `json:"available_in_metros,omitempty"`

	Class string `json:"class,omitempty"`

	Description string `json:"description,omitempty"`

	DeploymentTypes []string `json:"deployment_types,omitempty"`

	Id string `json:"id,omitempty"`

	Legacy bool `json:"legacy,omitempty"`

	Line string `json:"line,omitempty"`

	Name string `json:"name,omitempty"`

	Pricing map[string]interface{} `json:"pricing,omitempty"`

	Slug string `json:"slug,omitempty"`

	Specs FindDeviceById200ResponsePlanSpecs `json:"specs,omitempty"`

	// The plan type
	Type string `json:"type,omitempty"`
}
