/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// FindMetros - Retrieve all metros
func FindMetros(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetMetro - Retrieve a specific Metro's details
func GetMetro(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
