/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateAPIKey - Create a API key
func CreateAPIKey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateProjectAPIKey - Create an API key for a project.
func CreateProjectAPIKey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteAPIKey - Delete the API key
func DeleteAPIKey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteUserAPIKey - Delete the API key
func DeleteUserAPIKey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindAPIKeys - Retrieve all user API keys
func FindAPIKeys(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindProjectAPIKeys - Retrieve all API keys for the project.
func FindProjectAPIKeys(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
