/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CheckCapacityForFacility - Check capacity
func CheckCapacityForFacility(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CheckCapacityForMetro - Check capacity for a metro
func CheckCapacityForMetro(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindCapacityForFacility - View capacity
func FindCapacityForFacility(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindCapacityForMetro - View capacity for metros
func FindCapacityForMetro(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindOrganizationCapacityPerFacility - View available hardware plans per Facility for given organization
func FindOrganizationCapacityPerFacility(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindOrganizationCapacityPerMetro - View available hardware plans per Metro for given organization
func FindOrganizationCapacityPerMetro(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
