/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateInterconnectionPortVirtualCircuit - Create a new Virtual Circuit
func CreateInterconnectionPortVirtualCircuit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateOrganizationInterconnection - Request a new interconnection for the organization
func CreateOrganizationInterconnection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateProjectInterconnection - Request a new interconnection for the project's organization
func CreateProjectInterconnection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteInterconnection - Delete interconnection
func DeleteInterconnection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteVirtualCircuit - Delete a virtual circuit
func DeleteVirtualCircuit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetInterconnection - Get interconnection
func GetInterconnection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetInterconnectionPort - Get a interconnection port
func GetInterconnectionPort(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetVirtualCircuit - Get a virtual circuit
func GetVirtualCircuit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListInterconnectionPortVirtualCircuits - List a interconnection port's virtual circuits
func ListInterconnectionPortVirtualCircuits(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListInterconnectionPorts - List a interconnection's ports
func ListInterconnectionPorts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// OrganizationListInterconnections - List organization connections
func OrganizationListInterconnections(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ProjectListInterconnections - List project connections
func ProjectListInterconnections(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateInterconnection - Update interconnection
func UpdateInterconnection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateVirtualCircuit - Update a virtual circuit
func UpdateVirtualCircuit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
