/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateUser - Create a user
func CreateUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindCurrentUser - Retrieve the current user
func FindCurrentUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindInvitations - Retrieve current user invitations
func FindInvitations(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindUserById - Retrieve a user
func FindUserById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindUserCustomdata - Retrieve the custom metadata of a user
func FindUserCustomdata(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindUsers - Retrieve all users
func FindUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateCurrentUser - Update the current user
func UpdateCurrentUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
