/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"os"
	"time"
)

type Organization struct {
	Address FindDeviceById200ResponseFacilityAddress `json:"address,omitempty"`

	BillingAddress FindDeviceById200ResponseFacilityAddress `json:"billing_address,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	CreditAmount float32 `json:"credit_amount,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Description string `json:"description,omitempty"`

	// Force to all members to have enabled the two factor authentication after that date, unless the value is null
	Enforce2faAt time.Time `json:"enforce_2fa_at,omitempty"`

	Id string `json:"id,omitempty"`

	Logo *os.File `json:"logo,omitempty"`

	Members []FindBatchById200ResponseDevicesInner `json:"members,omitempty"`

	Memberships []FindBatchById200ResponseDevicesInner `json:"memberships,omitempty"`

	Name string `json:"name,omitempty"`

	Projects []FindBatchById200ResponseDevicesInner `json:"projects,omitempty"`

	Terms int32 `json:"terms,omitempty"`

	Twitter string `json:"twitter,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	Website string `json:"website,omitempty"`
}
