/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type CreateDeviceBatchRequestBatchesInner struct {
	AlwaysPxe bool `json:"always_pxe,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Description string `json:"description,omitempty"`

	// Array of facility codes the batch can use for provisioning. This param also takes a string if you want the batch to be fulfilled in only one facility. Cannot be set if the metro is already set.
	Facility []string `json:"facility,omitempty"`

	Features []string `json:"features,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	Hostnames []string `json:"hostnames,omitempty"`

	IpAddresses []CreateDeviceBatchRequestBatchesInnerIpAddressesInner `json:"ip_addresses,omitempty"`

	Locked bool `json:"locked,omitempty"`

	// The metro ID or code the batch can use for provisioning. Cannot be set if the facility is already set.
	Metro string `json:"metro,omitempty"`

	NoSshKeys bool `json:"no_ssh_keys,omitempty"`

	OperatingSystem string `json:"operating_system,omitempty"`

	Plan string `json:"plan,omitempty"`

	ProjectSshKeys []string `json:"project_ssh_keys,omitempty"`

	Tags []string `json:"tags,omitempty"`

	TerminationTime time.Time `json:"termination_time,omitempty"`

	// The UUIDs of users whose SSH keys should be included on the provisioned device.
	UserSshKeys []string `json:"user_ssh_keys,omitempty"`

	Userdata string `json:"userdata,omitempty"`
}
