/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type UpdateDeviceRequest struct {
	AlwaysPxe bool `json:"always_pxe,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	Description string `json:"description,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	IpxeScriptUrl string `json:"ipxe_script_url,omitempty"`

	Locked bool `json:"locked,omitempty"`

	// If true, this instance can not be converted to a different network type.
	NetworkFrozen bool `json:"network_frozen,omitempty"`

	SpotInstance bool `json:"spot_instance,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Userdata string `json:"userdata,omitempty"`
}
