/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type Metadata struct {
	Class string `json:"class,omitempty"`

	Customdata map[string]interface{} `json:"customdata,omitempty"`

	// The facility code of the instance
	Facility string `json:"facility,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	Id string `json:"id,omitempty"`

	Iqn string `json:"iqn,omitempty"`

	// The metro code of the instance
	Metro string `json:"metro,omitempty"`

	Network FindDeviceMetadataById200ResponseNetwork `json:"network,omitempty"`

	OperatingSystem map[string]interface{} `json:"operating_system,omitempty"`

	// The plan slug of the instance
	Plan string `json:"plan,omitempty"`

	// An array of the private subnets
	PrivateSubnets []string `json:"private_subnets,omitempty"`

	Reserved bool `json:"reserved,omitempty"`

	// The specs of the plan version of the instance
	Specs map[string]interface{} `json:"specs,omitempty"`

	SshKeys []string `json:"ssh_keys,omitempty"`

	SwitchShortId string `json:"switch_short_id,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Volumes []string `json:"volumes,omitempty"`
}
