/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type MoveHardwareReservation201Response struct {
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Amount that will be charged for every billing_cycle.
	CustomRate float32 `json:"custom_rate,omitempty"`

	Device FindDeviceById200Response `json:"device,omitempty"`

	Facility FindDeviceById200ResponseFacility `json:"facility,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	// Whether this Device requires assistance from Metal Equinix.
	NeedOfService bool `json:"need_of_service,omitempty"`

	Plan FindDeviceById200ResponsePlan `json:"plan,omitempty"`

	Project GetInterconnection200ResponsePortsInnerVirtualCircuitsVirtualCircuitsInnerAnyOf1VrfProject `json:"project,omitempty"`

	// Whether the reserved server is provisionable or not. Spare devices can't be provisioned unless they are activated first.
	Provisionable bool `json:"provisionable,omitempty"`

	// Short version of the ID.
	ShortId string `json:"short_id,omitempty"`

	// Whether the Hardware Reservation is a spare. Spare Hardware Reservations are used when a Hardware Reservations requires service from Metal Equinix
	Spare bool `json:"spare,omitempty"`

	// Switch short id. This can be used to determine if two devices are connected to the same switch, for example.
	SwitchUuid string `json:"switch_uuid,omitempty"`
}
