/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type FindSelfServiceReservations200ResponseReservationsInnerItemInner struct {
	Amount float32 `json:"amount,omitempty"`

	Id string `json:"id,omitempty"`

	MetroCode string `json:"metro_code,omitempty"`

	MetroId string `json:"metro_id,omitempty"`

	MetroName string `json:"metro_name,omitempty"`

	PlanId string `json:"plan_id,omitempty"`

	PlanName string `json:"plan_name,omitempty"`

	PlanSlug string `json:"plan_slug,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Term string `json:"term,omitempty"`
}
