/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type FindProjectApiKeys200ResponseApiKeysInner struct {
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Available only for API keys
	Description string `json:"description,omitempty"`

	Id string `json:"id,omitempty"`

	Project FindProjectApiKeys200ResponseApiKeysInnerProject `json:"project,omitempty"`

	ReadOnly bool `json:"read_only,omitempty"`

	Token string `json:"token,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	User FindProjectApiKeys200ResponseApiKeysInnerUser `json:"user,omitempty"`
}
