/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"time"
)

type SpotMarketRequestCreateInput struct {
	DevicesMax int32 `json:"devices_max,omitempty"`

	DevicesMin int32 `json:"devices_min,omitempty"`

	EndAt time.Time `json:"end_at,omitempty"`

	Facilities []string `json:"facilities,omitempty"`

	InstanceAttributes CreateSpotMarketRequestRequestInstanceAttributes `json:"instance_attributes,omitempty"`

	MaxBidPrice float32 `json:"max_bid_price,omitempty"`

	// The metro ID or code the spot market request will be created in.
	Metro string `json:"metro,omitempty"`
}
