/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetwork struct {
	AssignedTo FindBatchById200ResponseDevicesInner `json:"assigned_to,omitempty"`

	// True if the virtual network is attached to a virtual circuit. False if not.
	AssignedToVirtualCircuit bool `json:"assigned_to_virtual_circuit,omitempty"`

	Description string `json:"description,omitempty"`

	Facility FindBatchById200ResponseDevicesInner `json:"facility,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	// A list of instances with ports currently associated to this Virtual Network.
	Instances []FindBatchById200ResponseDevicesInner `json:"instances,omitempty"`

	// A list of metal gateways currently associated to this Virtual Network.
	MetalGateways []FindDeviceById200ResponseNetworkPortsInnerNativeVirtualNetworkMetalGatewaysInner `json:"metal_gateways,omitempty"`

	Metro FindBatchById200ResponseDevicesInner `json:"metro,omitempty"`

	// The Metro code of the metro in which this Virtual Network is defined.
	MetroCode string `json:"metro_code,omitempty"`

	Vxlan int32 `json:"vxlan,omitempty"`
}
