/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

type SelfServiceReservationItemRequest struct {
	Amount float32 `json:"amount,omitempty"`

	MetroId string `json:"metro_id,omitempty"`

	PlanId string `json:"plan_id,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Term string `json:"term,omitempty"`
}
