/*
 * Metal API
 *
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.
 *
 * API version: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package startapi

import (
	"fmt"
	metal "github.com/equinix-labs/metal-go/metal/v1"
	"github.com/gin-gonic/gin"
	"net/http"
	"time"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()

	// add timeout middleware with 12 second duration
	router.Use(timeoutMiddleware(time.Second * 100))
	for _, route := range routes {
		pattern := "/" + route.Name + route.Pattern
		switch route.Method {
		case http.MethodGet:
			router.GET(pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/metal/v1/",
		Index,
	},

	{
		"CreateAPIKey",
		http.MethodPost,
		"/metal/v1/user/api-keys",
		CreateAPIKey,
	},

	{
		"CreateProjectAPIKey",
		http.MethodPost,
		"/metal/v1/projects/:id/api-keys",
		CreateProjectAPIKey,
	},

	{
		"DeleteAPIKey",
		http.MethodDelete,
		"/metal/v1/api-keys/:id",
		DeleteAPIKey,
	},

	{
		"DeleteUserAPIKey",
		http.MethodDelete,
		"/metal/v1/user/api-keys/:id",
		DeleteUserAPIKey,
	},

	{
		"FindAPIKeys",
		http.MethodGet,
		"/metal/v1/user/api-keys",
		FindAPIKeys,
	},

	{
		"FindProjectAPIKeys",
		http.MethodGet,
		"/metal/v1/projects/:id/api-keys",
		FindProjectAPIKeys,
	},

	{
		"DeleteBgpSession",
		http.MethodDelete,
		"/metal/v1/bgp/sessions/:id",
		DeleteBgpSession,
	},

	{
		"FindBgpConfigByProject",
		http.MethodGet,
		"/metal/v1/projects/:id/bgp-config",
		FindBgpConfigByProject,
	},

	{
		"FindBgpSessionById",
		http.MethodGet,
		"/metal/v1/bgp/sessions/:id",
		FindBgpSessionById,
	},

	{
		"FindGlobalBgpRanges",
		http.MethodGet,
		"/metal/v1/projects/:id/global-bgp-ranges",
		FindGlobalBgpRanges,
	},

	{
		"FindProjectBgpSessions",
		http.MethodGet,
		"/metal/v1/projects/:id/bgp/sessions",
		FindProjectBgpSessions,
	},

	{
		"RequestBgpConfig",
		http.MethodPost,
		"/metal/v1/projects/:id/bgp-configs",
		RequestBgpConfig,
	},

	{
		"UpdateBgpSession",
		http.MethodPut,
		"/metal/v1/bgp/sessions/:id",
		UpdateBgpSession,
	},

	{
		"CreateDeviceBatch",
		http.MethodPost,
		"/metal/v1/projects/:id/devices/batch",
		CreateDeviceBatch,
	},

	{
		"DeleteBatch",
		http.MethodDelete,
		"/metal/v1/batches/:id",
		DeleteBatch,
	},

	{
		"FindBatchById",
		http.MethodGet,
		"/metal/v1/batches/:id",
		FindBatchById,
	},

	{
		"FindBatchesByProject",
		http.MethodGet,
		"/metal/v1/projects/:id/batches",
		FindBatchesByProject,
	},

	{
		"CheckCapacityForFacility",
		http.MethodPost,
		"/metal/v1/capacity",
		CheckCapacityForFacility,
	},

	{
		"CheckCapacityForMetro",
		http.MethodPost,
		"/metal/v1/capacity/metros",
		CheckCapacityForMetro,
	},

	{
		"FindCapacityForFacility",
		http.MethodGet,
		"/metal/v1/capacity",
		FindCapacityForFacility,
	},

	{
		"FindCapacityForMetro",
		http.MethodGet,
		"/metal/v1/capacity/metros",
		FindCapacityForMetro,
	},

	{
		"FindOrganizationCapacityPerFacility",
		http.MethodGet,
		"/metal/v1/organizations/:id/capacity",
		FindOrganizationCapacityPerFacility,
	},

	{
		"FindOrganizationCapacityPerMetro",
		http.MethodGet,
		"/metal/v1/organizations/:id/capacity/metros",
		FindOrganizationCapacityPerMetro,
	},

	{
		"CreateBgpSession",
		http.MethodPost,
		"/metal/v1/devices/:id/bgp/sessions",
		CreateBgpSession,
	},

	{
		"CreateDevice",
		http.MethodPost,
		"/metal/v1/projects/:id/devices",
		CreateDevice,
	},

	{
		"CreateIPAssignment",
		http.MethodPost,
		"/metal/v1/devices/:id/ips",
		CreateIPAssignment,
	},

	{
		"DeleteDevice",
		http.MethodDelete,
		"/metal/v1/devices/:id",
		DeleteDevice,
	},

	{
		"FindBgpSessions",
		http.MethodGet,
		"/metal/v1/devices/:id/bgp/sessions",
		FindBgpSessions,
	},

	{
		"FindDeviceById",
		http.MethodGet,
		"/metal/v1/devices/:id",
		FindDeviceById,
	},

	{
		"FindDeviceCustomdata",
		http.MethodGet,
		"/metal/v1/devices/:id/customdata",
		FindDeviceCustomdata,
	},

	{
		"FindDeviceMetadataByID",
		http.MethodGet,
		"/metal/v1/devices/:id/metadata",
		FindDeviceMetadataByID,
	},

	{
		"FindDeviceUserdataByID",
		http.MethodGet,
		"/metal/v1/devices/:id/userdata",
		FindDeviceUserdataByID,
	},

	{
		"FindIPAssignmentCustomdata",
		http.MethodGet,
		"/metal/v1/devices/:instance_id/ips/:id/customdata",
		FindIPAssignmentCustomdata,
	},

	{
		"FindIPAssignments",
		http.MethodGet,
		"/metal/v1/devices/:id/ips",
		FindIPAssignments,
	},

	{
		"FindInstanceBandwidth",
		http.MethodGet,
		"/metal/v1/devices/:id/bandwidth",
		FindInstanceBandwidth,
	},

	{
		"FindOrganizationDevices",
		http.MethodGet,
		"/metal/v1/organizations/:id/devices",
		FindOrganizationDevices,
	},

	{
		"FindProjectDevices",
		http.MethodGet,
		"/metal/v1/projects/:id/devices",
		FindProjectDevices,
	},

	{
		"FindTraffic",
		http.MethodGet,
		"/metal/v1/devices/:id/traffic",
		FindTraffic,
	},

	{
		"GetBgpNeighborData",
		http.MethodGet,
		"/metal/v1/devices/:id/bgp/neighbors",
		GetBgpNeighborData,
	},

	{
		"PerformAction",
		http.MethodPost,
		"/metal/v1/devices/:id/actions",
		PerformAction,
	},

	{
		"UpdateDevice",
		http.MethodPut,
		"/metal/v1/devices/:id",
		UpdateDevice,
	},

	{
		"CreateEmail",
		http.MethodPost,
		"/metal/v1/emails",
		CreateEmail,
	},

	{
		"DeleteEmail",
		http.MethodDelete,
		"/metal/v1/emails/:id",
		DeleteEmail,
	},

	{
		"FindEmailById",
		http.MethodGet,
		"/metal/v1/emails/:id",
		FindEmailById,
	},

	{
		"UpdateEmail",
		http.MethodPut,
		"/metal/v1/emails/:id",
		UpdateEmail,
	},

	{
		"FindDeviceEvents",
		http.MethodGet,
		"/metal/v1/devices/:id/events",
		FindDeviceEvents,
	},

	{
		"FindEventById",
		http.MethodGet,
		"/metal/v1/events/:id",
		FindEventById,
	},

	{
		"FindEvents",
		http.MethodGet,
		"/metal/v1/events",
		FindEvents,
	},

	{
		"FindInterconnectionEvents",
		http.MethodGet,
		"/metal/v1/connections/:connection_id/events",
		FindInterconnectionEvents,
	},

	{
		"FindInterconnectionPortEvents",
		http.MethodGet,
		"/metal/v1/connections/:connection_id/ports/:id/events",
		FindInterconnectionPortEvents,
	},

	{
		"FindOrganizationEvents",
		http.MethodGet,
		"/metal/v1/organizations/:id/events",
		FindOrganizationEvents,
	},

	{
		"FindProjectEvents",
		http.MethodGet,
		"/metal/v1/projects/:id/events",
		FindProjectEvents,
	},

	{
		"FindVirtualCircuitEvents",
		http.MethodGet,
		"/metal/v1/virtual-circuit/:id/events",
		FindVirtualCircuitEvents,
	},

	{
		"FindFacilities",
		http.MethodGet,
		"/metal/v1/facilities",
		FindFacilities,
	},

	{
		"FindFacilitiesByOrganization",
		http.MethodGet,
		"/metal/v1/organizations/:id/facilities",
		FindFacilitiesByOrganization,
	},

	{
		"FindFacilitiesByProject",
		http.MethodGet,
		"/metal/v1/projects/:id/facilities",
		FindFacilitiesByProject,
	},

	{
		"FindHardwareReservationById",
		http.MethodGet,
		"/metal/v1/hardware-reservations/:id",
		FindHardwareReservationById,
	},

	{
		"FindProjectHardwareReservations",
		http.MethodGet,
		"/metal/v1/projects/:id/hardware-reservations",
		FindProjectHardwareReservations,
	},

	{
		"MoveHardwareReservation",
		http.MethodPost,
		"/metal/v1/hardware-reservations/:id/move",
		MoveHardwareReservation,
	},

	{
		"DeleteIPAddress",
		http.MethodDelete,
		"/metal/v1/ips/:id",
		DeleteIPAddress,
	},

	{
		"FindIPAddressById",
		http.MethodGet,
		"/metal/v1/ips/:id",
		FindIPAddressById,
	},

	{
		"FindIPAddressCustomdata",
		http.MethodGet,
		"/metal/v1/ips/:id/customdata",
		FindIPAddressCustomdata,
	},

	{
		"FindIPAvailabilities",
		http.MethodGet,
		"/metal/v1/ips/:id/available",
		FindIPAvailabilities,
	},

	{
		"FindIPReservations",
		http.MethodGet,
		"/metal/v1/projects/:id/ips",
		FindIPReservations,
	},

	{
		"RequestIPReservation",
		http.MethodPost,
		"/metal/v1/projects/:id/ips",
		RequestIPReservation,
	},

	{
		"UpdateIPAddress",
		http.MethodPatch,
		"/metal/v1/ips/:id",
		UpdateIPAddress,
	},

	{
		"FindIncidents",
		http.MethodGet,
		"/metal/v1/incidents",
		FindIncidents,
	},

	{
		"CreateInterconnectionPortVirtualCircuit",
		http.MethodPost,
		"/metal/v1/connections/:connection_id/ports/:port_id/virtual-circuits",
		CreateInterconnectionPortVirtualCircuit,
	},

	{
		"CreateOrganizationInterconnection",
		http.MethodPost,
		"/metal/v1/organizations/:organization_id/connections",
		CreateOrganizationInterconnection,
	},

	{
		"CreateProjectInterconnection",
		http.MethodPost,
		"/metal/v1/projects/:project_id/connections",
		CreateProjectInterconnection,
	},

	{
		"DeleteInterconnection",
		http.MethodDelete,
		"/metal/v1/connections/:connection_id",
		DeleteInterconnection,
	},

	{
		"DeleteVirtualCircuit",
		http.MethodDelete,
		"/metal/v1/virtual-circuits/:id",
		DeleteVirtualCircuit,
	},

	{
		"GetInterconnection",
		http.MethodGet,
		"/metal/v1/connections/:connection_id",
		GetInterconnection,
	},

	{
		"GetInterconnectionPort",
		http.MethodGet,
		"/metal/v1/connections/:connection_id/ports/:id",
		GetInterconnectionPort,
	},

	{
		"GetVirtualCircuit",
		http.MethodGet,
		"/metal/v1/virtual-circuits/:id",
		GetVirtualCircuit,
	},

	{
		"ListInterconnectionPortVirtualCircuits",
		http.MethodGet,
		"/metal/v1/connections/:connection_id/ports/:port_id/virtual-circuits",
		ListInterconnectionPortVirtualCircuits,
	},

	{
		"ListInterconnectionPorts",
		http.MethodGet,
		"/metal/v1/connections/:connection_id/ports",
		ListInterconnectionPorts,
	},

	{
		"OrganizationListInterconnections",
		http.MethodGet,
		"/metal/v1/organizations/:organization_id/connections",
		OrganizationListInterconnections,
	},

	{
		"ProjectListInterconnections",
		http.MethodGet,
		"/metal/v1/projects/:project_id/connections",
		ProjectListInterconnections,
	},

	{
		"UpdateInterconnection",
		http.MethodPut,
		"/metal/v1/connections/:connection_id",
		UpdateInterconnection,
	},

	{
		"UpdateVirtualCircuit",
		http.MethodPut,
		"/metal/v1/virtual-circuits/:id",
		UpdateVirtualCircuit,
	},

	{
		"AcceptInvitation",
		http.MethodPut,
		"/metal/v1/invitations/:id",
		AcceptInvitation,
	},

	{
		"DeclineInvitation",
		http.MethodDelete,
		"/metal/v1/invitations/:id",
		DeclineInvitation,
	},

	{
		"FindInvitationById",
		http.MethodGet,
		"/metal/v1/invitations/:id",
		FindInvitationById,
	},

	{
		"CreateLicense",
		http.MethodPost,
		"/metal/v1/projects/:id/licenses",
		CreateLicense,
	},

	{
		"DeleteLicense",
		http.MethodDelete,
		"/metal/v1/licenses/:id",
		DeleteLicense,
	},

	{
		"FindLicenseById",
		http.MethodGet,
		"/metal/v1/licenses/:id",
		FindLicenseById,
	},

	{
		"FindProjectLicenses",
		http.MethodGet,
		"/metal/v1/projects/:id/licenses",
		FindProjectLicenses,
	},

	{
		"UpdateLicense",
		http.MethodPut,
		"/metal/v1/licenses/:id",
		UpdateLicense,
	},

	{
		"DeleteMembership",
		http.MethodDelete,
		"/metal/v1/memberships/:id",
		DeleteMembership,
	},

	{
		"FindMembershipById",
		http.MethodGet,
		"/metal/v1/memberships/:id",
		FindMembershipById,
	},

	{
		"UpdateMembership",
		http.MethodPut,
		"/metal/v1/memberships/:id",
		UpdateMembership,
	},

	{
		"CreateMetalGateway",
		http.MethodPost,
		"/metal/v1/projects/:project_id/metal-gateways",
		CreateMetalGateway,
	},

	{
		"DeleteMetalGateway",
		http.MethodDelete,
		"/metal/v1/metal-gateways/:id",
		DeleteMetalGateway,
	},

	{
		"FindMetalGatewayById",
		http.MethodGet,
		"/metal/v1/metal-gateways/:id",
		FindMetalGatewayById,
	},

	{
		"FindMetalGatewaysByProject",
		http.MethodGet,
		"/metal/v1/projects/:project_id/metal-gateways",
		FindMetalGatewaysByProject,
	},

	{
		"FindMetros",
		http.MethodGet,
		"/metal/v1/locations/metros",
		FindMetros,
	},

	{
		"GetMetro",
		http.MethodGet,
		"/metal/v1/locations/metros/:id",
		GetMetro,
	},

	{
		"FindEnsureOtp",
		http.MethodPost,
		"/metal/v1/user/otp/verify/:otp",
		FindEnsureOtp,
	},

	{
		"FindRecoveryCodes",
		http.MethodGet,
		"/metal/v1/user/otp/recovery-codes",
		FindRecoveryCodes,
	},

	{
		"ReceiveCodes",
		http.MethodPost,
		"/metal/v1/user/otp/sms/receive",
		ReceiveCodes,
	},

	{
		"RegenerateCodes",
		http.MethodPost,
		"/metal/v1/user/otp/recovery-codes",
		RegenerateCodes,
	},

	{
		"FindOperatingSystemVersion",
		http.MethodGet,
		"/metal/v1/operating-system-versions",
		FindOperatingSystemVersion,
	},

	{
		"FindOperatingSystems",
		http.MethodGet,
		"/metal/v1/operating-systems",
		FindOperatingSystems,
	},

	{
		"CreateOrganization",
		http.MethodPost,
		"/metal/v1/organizations",
		CreateOrganization,
	},

	{
		"CreateOrganizationInvitation",
		http.MethodPost,
		"/metal/v1/organizations/:id/invitations",
		CreateOrganizationInvitation,
	},

	{
		"CreateOrganizationProject",
		http.MethodPost,
		"/metal/v1/organizations/:id/projects",
		CreateOrganizationProject,
	},

	{
		"CreatePaymentMethod",
		http.MethodPost,
		"/metal/v1/organizations/:id/payment-methods",
		CreatePaymentMethod,
	},

	{
		"DeleteOrganization",
		http.MethodDelete,
		"/metal/v1/organizations/:id",
		DeleteOrganization,
	},

	{
		"FindOperatingSystemsByOrganization",
		http.MethodGet,
		"/metal/v1/organizations/:id/operating-systems",
		FindOperatingSystemsByOrganization,
	},

	{
		"FindOrganizationById",
		http.MethodGet,
		"/metal/v1/organizations/:id",
		FindOrganizationById,
	},

	{
		"FindOrganizationCustomdata",
		http.MethodGet,
		"/metal/v1/organizations/:id/customdata",
		FindOrganizationCustomdata,
	},

	{
		"FindOrganizationInvitations",
		http.MethodGet,
		"/metal/v1/organizations/:id/invitations",
		FindOrganizationInvitations,
	},

	{
		"FindOrganizationPaymentMethods",
		http.MethodGet,
		"/metal/v1/organizations/:id/payment-methods",
		FindOrganizationPaymentMethods,
	},

	{
		"FindOrganizationProjects",
		http.MethodGet,
		"/metal/v1/organizations/:id/projects",
		FindOrganizationProjects,
	},

	{
		"FindOrganizationTransfers",
		http.MethodGet,
		"/metal/v1/organizations/:id/transfers",
		FindOrganizationTransfers,
	},

	{
		"FindOrganizations",
		http.MethodGet,
		"/metal/v1/organizations",
		FindOrganizations,
	},

	{
		"FindPlansByOrganization",
		http.MethodGet,
		"/metal/v1/organizations/:id/plans",
		FindPlansByOrganization,
	},

	{
		"UpdateOrganization",
		http.MethodPut,
		"/metal/v1/organizations/:id",
		UpdateOrganization,
	},

	{
		"CreatePasswordResetToken",
		http.MethodPost,
		"/metal/v1/reset-password",
		CreatePasswordResetToken,
	},

	{
		"ResetPassword",
		http.MethodDelete,
		"/metal/v1/reset-password",
		ResetPassword,
	},

	{
		"DeletePaymentMethod",
		http.MethodDelete,
		"/metal/v1/payment-methods/:id",
		DeletePaymentMethod,
	},

	{
		"FindPaymentMethodById",
		http.MethodGet,
		"/metal/v1/payment-methods/:id",
		FindPaymentMethodById,
	},

	{
		"UpdatePaymentMethod",
		http.MethodPut,
		"/metal/v1/payment-methods/:id",
		UpdatePaymentMethod,
	},

	{
		"FindPlans",
		http.MethodGet,
		"/metal/v1/plans",
		FindPlans,
	},

	{
		"FindPlansByProject",
		http.MethodGet,
		"/metal/v1/projects/:id/plans",
		FindPlansByProject,
	},

	{
		"AssignNativeVlan",
		http.MethodPost,
		"/metal/v1/ports/:id/native-vlan",
		AssignNativeVlan,
	},

	{
		"AssignPort",
		http.MethodPost,
		"/metal/v1/ports/:id/assign",
		AssignPort,
	},

	{
		"BondPort",
		http.MethodPost,
		"/metal/v1/ports/:id/bond",
		BondPort,
	},

	{
		"ConvertLayer2",
		http.MethodPost,
		"/metal/v1/ports/:id/convert/layer-2",
		ConvertLayer2,
	},

	{
		"ConvertLayer3",
		http.MethodPost,
		"/metal/v1/ports/:id/convert/layer-3",
		ConvertLayer3,
	},

	{
		"CreatePortVlanAssignmentBatch",
		http.MethodPost,
		"/metal/v1/ports/:id/vlan-assignments/batches",
		CreatePortVlanAssignmentBatch,
	},

	{
		"DeleteNativeVlan",
		http.MethodDelete,
		"/metal/v1/ports/:id/native-vlan",
		DeleteNativeVlan,
	},

	{
		"DisbondPort",
		http.MethodPost,
		"/metal/v1/ports/:id/disbond",
		DisbondPort,
	},

	{
		"FindPortById",
		http.MethodGet,
		"/metal/v1/ports/:id",
		FindPortById,
	},

	{
		"FindPortVlanAssignmentBatchByPortIdAndBatchId",
		http.MethodGet,
		"/metal/v1/ports/:id/vlan-assignments/batches/:batch_id",
		FindPortVlanAssignmentBatchByPortIdAndBatchId,
	},

	{
		"FindPortVlanAssignmentBatches",
		http.MethodGet,
		"/metal/v1/ports/:id/vlan-assignments/batches",
		FindPortVlanAssignmentBatches,
	},

	{
		"FindPortVlanAssignmentByPortIdAndAssignmentId",
		http.MethodGet,
		"/metal/v1/ports/:id/vlan-assignments/:assignment_id",
		FindPortVlanAssignmentByPortIdAndAssignmentId,
	},

	{
		"FindPortVlanAssignments",
		http.MethodGet,
		"/metal/v1/ports/:id/vlan-assignments",
		FindPortVlanAssignments,
	},

	{
		"UnassignPort",
		http.MethodPost,
		"/metal/v1/ports/:id/unassign",
		UnassignPort,
	},

	{
		"CreateProject",
		http.MethodPost,
		"/metal/v1/projects",
		CreateProject,
	},

	{
		"CreateProjectInvitation",
		http.MethodPost,
		"/metal/v1/projects/:project_id/invitations",
		CreateProjectInvitation,
	},

	{
		"CreateTransferRequest",
		http.MethodPost,
		"/metal/v1/projects/:id/transfers",
		CreateTransferRequest,
	},

	{
		"DeleteProject",
		http.MethodDelete,
		"/metal/v1/projects/:id",
		DeleteProject,
	},

	{
		"FindIPReservationCustomdata",
		http.MethodGet,
		"/metal/v1/projects/:project_id/ips/:id/customdata",
		FindIPReservationCustomdata,
	},

	{
		"FindProjectById",
		http.MethodGet,
		"/metal/v1/projects/:id",
		FindProjectById,
	},

	{
		"FindProjectCustomdata",
		http.MethodGet,
		"/metal/v1/projects/:id/customdata",
		FindProjectCustomdata,
	},

	{
		"FindProjectInvitations",
		http.MethodGet,
		"/metal/v1/projects/:project_id/invitations",
		FindProjectInvitations,
	},

	{
		"FindProjectMemberships",
		http.MethodGet,
		"/metal/v1/projects/:project_id/memberships",
		FindProjectMemberships,
	},

	{
		"FindProjects",
		http.MethodGet,
		"/metal/v1/projects",
		FindProjects,
	},

	{
		"UpdateProject",
		http.MethodPut,
		"/metal/v1/projects/:id",
		UpdateProject,
	},

	{
		"CreateProjectSSHKey",
		http.MethodPost,
		"/metal/v1/projects/:id/ssh-keys",
		CreateProjectSSHKey,
	},

	{
		"CreateSSHKey",
		http.MethodPost,
		"/metal/v1/ssh-keys",
		CreateSSHKey,
	},

	{
		"DeleteSSHKey",
		http.MethodDelete,
		"/metal/v1/ssh-keys/:id",
		DeleteSSHKey,
	},

	{
		"FindDeviceSSHKeys",
		http.MethodGet,
		"/metal/v1/devices/:id/ssh-keys",
		FindDeviceSSHKeys,
	},

	{
		"FindProjectSSHKeys",
		http.MethodGet,
		"/metal/v1/projects/:id/ssh-keys",
		FindProjectSSHKeys,
	},

	{
		"FindSSHKeyById",
		http.MethodGet,
		"/metal/v1/ssh-keys/:id",
		FindSSHKeyById,
	},

	{
		"FindSSHKeys",
		http.MethodGet,
		"/metal/v1/ssh-keys",
		FindSSHKeys,
	},

	{
		"UpdateSSHKey",
		http.MethodPut,
		"/metal/v1/ssh-keys/:id",
		UpdateSSHKey,
	},

	{
		"CreateSelfServiceReservation",
		http.MethodPost,
		"/metal/v1/projects/:project_id/self-service/reservations",
		CreateSelfServiceReservation,
	},

	{
		"FindSelfServiceReservation",
		http.MethodGet,
		"/metal/v1/projects/:project_id/self-service/reservations/:id",
		FindSelfServiceReservation,
	},

	{
		"FindSelfServiceReservations",
		http.MethodGet,
		"/metal/v1/projects/:project_id/self-service/reservations",
		FindSelfServiceReservations,
	},

	{
		"CreateSpotMarketRequest",
		http.MethodPost,
		"/metal/v1/projects/:id/spot-market-requests",
		CreateSpotMarketRequest,
	},

	{
		"DeleteSpotMarketRequest",
		http.MethodDelete,
		"/metal/v1/spot-market-requests/:id",
		DeleteSpotMarketRequest,
	},

	{
		"FindMetroSpotMarketPrices",
		http.MethodGet,
		"/metal/v1/market/spot/prices/metros",
		FindMetroSpotMarketPrices,
	},

	{
		"FindSpotMarketPrices",
		http.MethodGet,
		"/metal/v1/market/spot/prices",
		FindSpotMarketPrices,
	},

	{
		"FindSpotMarketPricesHistory",
		http.MethodGet,
		"/metal/v1/market/spot/prices/history",
		FindSpotMarketPricesHistory,
	},

	{
		"FindSpotMarketRequestById",
		http.MethodGet,
		"/metal/v1/spot-market-requests/:id",
		FindSpotMarketRequestById,
	},

	{
		"ListSpotMarketRequests",
		http.MethodGet,
		"/metal/v1/projects/:id/spot-market-requests",
		ListSpotMarketRequests,
	},

	{
		"RequestSuppert",
		http.MethodPost,
		"/metal/v1/support-requests",
		RequestSuppert,
	},

	{
		"AcceptTransferRequest",
		http.MethodPut,
		"/metal/v1/transfers/:id",
		AcceptTransferRequest,
	},

	{
		"DeclineTransferRequest",
		http.MethodDelete,
		"/metal/v1/transfers/:id",
		DeclineTransferRequest,
	},

	{
		"FindTransferRequestById",
		http.MethodGet,
		"/metal/v1/transfers/:id",
		FindTransferRequestById,
	},

	{
		"DisableTfaApp",
		http.MethodDelete,
		"/metal/v1/user/otp/app",
		DisableTfaApp,
	},

	{
		"DisableTfaSms",
		http.MethodDelete,
		"/metal/v1/user/otp/sms",
		DisableTfaSms,
	},

	{
		"EnableTfaApp",
		http.MethodPost,
		"/metal/v1/user/otp/app",
		EnableTfaApp,
	},

	{
		"EnableTfaSms",
		http.MethodPost,
		"/metal/v1/user/otp/sms",
		EnableTfaSms,
	},

	{
		"FindDeviceUsages",
		http.MethodGet,
		"/metal/v1/devices/:id/usages",
		FindDeviceUsages,
	},

	{
		"FindProjectUsage",
		http.MethodGet,
		"/metal/v1/projects/:id/usages",
		FindProjectUsage,
	},

	{
		"ConsumeVerificationRequest",
		http.MethodPut,
		"/metal/v1/verify-email",
		ConsumeVerificationRequest,
	},

	{
		"CreateValidationRequest",
		http.MethodPost,
		"/metal/v1/verify-email",
		CreateValidationRequest,
	},

	{
		"ValidateUserdata",
		http.MethodPost,
		"/metal/v1/userdata/validate",
		ValidateUserdata,
	},

	{
		"CreateUser",
		http.MethodPost,
		"/metal/v1/users",
		CreateUser,
	},

	{
		"FindCurrentUser",
		http.MethodGet,
		"/metal/v1/user",
		FindCurrentUser,
	},

	{
		"FindInvitations",
		http.MethodGet,
		"/metal/v1/invitations",
		FindInvitations,
	},

	{
		"FindUserById",
		http.MethodGet,
		"/metal/v1/users/:id",
		FindUserById,
	},

	{
		"FindUserCustomdata",
		http.MethodGet,
		"/metal/v1/users/:id/customdata",
		FindUserCustomdata,
	},

	{
		"FindUsers",
		http.MethodGet,
		"/metal/v1/users",
		FindUsers,
	},

	{
		"UpdateCurrentUser",
		http.MethodPut,
		"/metal/v1/user",
		UpdateCurrentUser,
	},

	{
		"CreateVirtualNetwork",
		http.MethodPost,
		"/metal/v1/projects/:id/virtual-networks",
		CreateVirtualNetwork,
	},

	{
		"DeleteVirtualNetwork",
		http.MethodDelete,
		"/metal/v1/virtual-networks/:id",
		DeleteVirtualNetwork,
	},

	{
		"FindVirtualNetworks",
		http.MethodGet,
		"/metal/v1/projects/:id/virtual-networks",
		FindVirtualNetworks,
	},

	{
		"GetVirtualNetwork",
		http.MethodGet,
		"/metal/v1/virtual-networks/:id",
		GetVirtualNetwork,
	},

	{
		"CreateVrf",
		http.MethodPost,
		"/metal/v1/projects/:id/vrfs",
		CreateVrf,
	},

	{
		"DeleteVrf",
		http.MethodDelete,
		"/metal/v1/vrfs/:id",
		DeleteVrf,
	},

	{
		"FindVrfById",
		http.MethodGet,
		"/metal/v1/vrfs/:id",
		FindVrfById,
	},

	{
		"FindVrfIpReservations",
		http.MethodGet,
		"/metal/v1/vrfs/:id/ips",
		FindVrfIpReservations,
	},

	{
		"FindVrfs",
		http.MethodGet,
		"/metal/v1/projects/:id/vrfs",
		FindVrfs,
	},

	{
		"UpdateVrf",
		http.MethodPut,
		"/metal/v1/vrfs/:id",
		UpdateVrf,
	},
}

var configuration *metal.Configuration
var apiClient *metal.APIClient
var include = []string{}
var exclude = []string{"available_in"}

func init() {
	configuration = metal.NewConfiguration()
	configuration.Debug = true
	configuration.AddDefaultHeader("X-Auth-Token", "h9FYNNnc3sbdcSr3PUyptriEyRQPqwhg")
	apiClient = metal.NewAPIClient(configuration)
}

func ErrorCheck(err error, r *http.Response, c *gin.Context) bool {
	if err != nil {
		errmsg := fmt.Sprintf("Error when calling ``: %v\n", err)
		msg := fmt.Sprintf("Full HTTP response: %v\n", r)
		c.JSON(http.StatusBadRequest, gin.H{"errmsg": errmsg, "msg": msg})
		return false
	}
	return true
}
